feat: failure recovery

diff --git a/.github/workflows/hello-devops.yml b/.github/workflows/hello-devops.yml
--- a/.github/workflows/hello-devops.yml
+++ b/.github/workflows/hello-devops.yml
@@ -77,7 +77,7 @@ jobs:
     needs: build # This is the magic Link
     steps:
       - name: "Running Unit Tests"
-        run: echo "tests are Running... All Passed."
+        run: exit 1 #echo "tests are Running... All Passed."
 
   deploy-production:
     runs-on: ubuntu-latest
@@ -110,6 +110,17 @@ jobs:
 
           docker build -t $IMAGE_NAME .
           docker push $IMAGE_NAME
+
+  on-failure-alert:
+    runs-on: ubuntu-latest
+    needs: [build, test, container-build]
+    if: failure() # this is the secret sauce
+    steps:
+      - name: "Send Emergency Notification"
+        run: |
+          echo "PIPLINE FAILURE DETECTED"
+          echo "One of the critical stages failed."
+          echo "Investigating logs for ${{ github.sha }}..."
 
 
 
